=== JunhoYoon95/XML/Vehicle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"         
    xmlns:db = "http://db.kookmin.ac.kr"
    targetNamespace = "http://db.kookmin.ac.kr"
    elementFormDefault="qualified">
    
    <complexType name="DriveTrainType">
        <sequence>
            <element name = "Engine" type="string"/> 
            <element name = "Transmission" type="string"/>
        </sequence>
    </complexType>
    
    <complexType name = "VehicleType">
        <sequence>
            <element name = "Body" type="db:BodyType"/>
            <element name = "DriveTrain" type ="db:DriveTrainType"/>
        </sequence>
    </complexType>
    <element name = "Vehicle" type = "db:VehicleType"/> 
    
    <complexType name="AutomobileType">
        <complexContent>
            <extension base = "db:VehicleType">
                <sequence>
                    <element name = "Trunk" type ="db:TrunckType"/>
                </sequence>
            </extension>    
        </complexContent>
    </complexType>
    
    <complexType name="SedanType">
        <complexContent>
            <extension base="db:AutomobileType"/>            
        </complexContent>
    </complexType>
    
    <complexType name="ConvertibleType">
        <complexContent>
            <extension base="db:AutomobileType">
                <sequence>
                    <element name="OperatingRoof" type="db:OperatingRoofType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="TruckType">
        <complexContent>
            <extension base="db:VehicleType">
                <sequence>
                    <element name = "Compartment" type="db:CompartmentType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="TrunckType">
        <simpleContent>
            <extension base="string"></extension>
        </simpleContent>
    </complexType>
    
    <complexType name="OperatingRoofType">
        <simpleContent>
            <extension base="string"></extension>
        </simpleContent>
    </complexType>

    <complexType name="BodyType">
        <simpleContent>
            <extension base="string"></extension>
        </simpleContent>
    </complexType>
    
    <complexType name="CompartmentType">
        <simpleContent>
            <extension base="string"></extension>
        </simpleContent>
    </complexType>
    
    <element name="Vehicles">
        <complexType>
            <sequence>
                <element ref="db:Vehicle" minOccurs="0" maxOccurs ="unbounded"/>
            </sequence>
        </complexType>    
    </element>
</schema>

=== JunhoYoon95/XML/Vehivle.xml
<?xml version="1.0" encoding="UTF-8"?>
<report:Vehicles xmlns:report="http://db.kookmin.ac.kr"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://db.kookmin.ac.kr file:/Users/junhoyoon/Desktop/KMU/XML/Report/Vehicle.xsd">
    
    <report:Vehicle>
        <report:Automobile>
            <report:Body></report:Body>
            <report:DriveTrain>
                <report:Engine></report:Engine>
                <report:Transmission></report:Transmission>
            </report:DriveTrain>
            <report:Trunk></report:Trunk>
        </report:Automobile>
        <report:Sedan>
            <report:Body></report:Body>
            <report:DriveTrain>
                <report:Engine></report:Engine>
                <report:Transmission></report:Transmission>
            </report:DriveTrain>
            <report:Trunk></report:Trunk>
        </report:Sedan>
        <report:Convertible>
            <report:Body></report:Body>
            <report:DriveTrain>
                <report:Engine></report:Engine>
                <report:Transmission></report:Transmission>
            </report:DriveTrain>
            <report:Trunk></report:Trunk>
            <report:OperatingRoof></report:OperatingRoof>
        </report:Convertible>
        <report:Truck>
            <report:Body></report:Body>
            <report:DriveTrain>
                <report:Engine></report:Engine>
                <report:Transmission></report:Transmission>
            </report:DriveTrain>
            <report:Compartment></report:Compartment>
        </report:Truck>
    </report:Vehicle>
    
</report:Vehicles>

=== JunhoYoon95/XML/Vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>
<Vehicles xmlns="http://db.kookmin.ac.kr"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://db.kookmin.ac.kr file:/Users/junhoyoon/Desktop/KMU/XML/Report/Vehicle.xsd">
    <Vehicle xsi:type = "SedanType">
        
        <Body> White Genesis like </Body>
        <DriveTrain>
            <Engine> X6 </Engine>
            <Transmission> VCT </Transmission>
        </DriveTrain>
        <Trunk> None </Trunk>
    </Vehicle>
    
    <Vehicle xsi:type = "AutomobileType">
        <Body> Matt Black Maserati like </Body>
        <DriveTrain>
            <Engine> X4 </Engine>
            <Transmission> DCT </Transmission>
        </DriveTrain>
        <Trunk> Wide </Trunk>
    </Vehicle>
    
    <Vehicle xsi:type = "TruckType">
        <Body> Gray Starex like </Body>
        <DriveTrain>
            <Engine> X4 </Engine>
            <Transmission> DCT </Transmission>
        </DriveTrain>
        <Compartment> 9 </Compartment>
    </Vehicle>
    
    <Vehicle xsi:type = "ConvertibleType">
        <Body> Red Ferrari like, U know What I mean </Body>
        <DriveTrain>
            <Engine> X6 </Engine>
            <Transmission> DCT </Transmission>
        </DriveTrain>
        <Trunk> Narrow </Trunk>
        <OperatingRoof> Black Matt Roof </OperatingRoof>
    </Vehicle>
    
    <Vehicle xsi:type = "SedanType">
        <Body> silver Bentley like </Body>
        <DriveTrain>
            <Engine> X6 </Engine>
            <Transmission> DCT </Transmission>
        </DriveTrain>
        <Trunk> Wide </Trunk>
    </Vehicle>
</Vehicles>
